name: MLFlow CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  train-and-log-model:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run training script
      - name: Train and log model to MLFlow
        env:
          MLFLOW_TRACKING_URI: "http://127.0.0.1:5000"
        run: |
          python train.py

      # Step 5: Notify on success
      - name: Notify success
        if: success()
        run: echo "Model training completed successfully and logged to MLFlow."

  notify-failure:
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Notify failure
        run: echo "CI/CD pipeline failed!"
